### ISSUE TITLE
Colector Not Starting

### ISSUE THREAD

**Issue by nbaillie** [logicmonitor/docker_lm_collector#22]
Using a compose file like bellow on Swarm i get the error also bellow, when using the image "logicmonitor/collector:latest" from docker hub.

```
version: '3.2'
services:
  automated01:
    image: logicmonitor/collector:latest
    restart: always
    environment:
      account: 'xxxxx'
      access_id: 'xxxxx'
      access_key: 'xxxxx'
      collector_group: 'xxxxx'
      collector_size: "small"
      description: "xxxxx"
      cleanup: "true"
```

docker logs 5c2a2e10a2f8
DEBUG:root:finding collector Demo Server Collector
Traceback (most recent call last):
  File "/collector/startup.py", line 50, in <module>
    main()
  File "/collector/startup.py", line 46, in main
    startup(client, params)
  File "/collector/startup.py", line 14, in startup
    f = collector.find_collector(client, params)
  File "/collector/collector.py", line 100, in find_collector
    return find_collector_by_description(client, params)
  File "/collector/collector.py", line 142, in find_collector_by_description
    ' calling get_device_list: ' + str(e) + '\n'
UnboundLocalError: local variable 'e' referenced before assignment
